name: Testing

on:
  push:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pylint **/*.py

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pytest test
